import { Card } from './types';

export const INITIAL_CARDS: Card[] = [
  {
    id: '1',
    category: 'deep-talk',
    title: '心语时刻',
    content: '你最喜欢我们在一起的哪一个瞬间？为什么那个时刻让你印象深刻？',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '2',
    category: 'deep-talk',
    title: '心语时刻',
    content: '如果我们可以一起去任何地方旅行，不考虑预算，你会选哪里？',
    animal: 'Rabbit',
    color: 'bg-rose-50',
  },
  {
    id: '3',
    category: 'deep-talk',
    title: '心语时刻',
    content: '你觉得我身上最吸引你的三个特质是什么？',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '4',
    category: 'challenge',
    title: '森林挑战',
    content: '给对方一个长达30秒的拥抱，感受彼此的呼吸。',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '5',
    category: 'challenge',
    title: '森林挑战',
    content: '用三种不同的赞美词夸奖对方，每句都要看着对方的眼睛。',
    animal: 'Rabbit',
    color: 'bg-pink-50',
  },
  {
    id: '6',
    category: 'challenge',
    title: '森林挑战',
    content: '模仿对方平时最常说的一句话或一个小动作。',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '7',
    category: 'deep-talk',
    title: '心语时刻',
    content: '我们之间有什么小习惯是你觉得特别温馨、不想改变的？',
    animal: 'Koala',
    color: 'bg-teal-50',
  },
  {
    id: '8',
    category: 'wisdom',
    title: '森林寄语',
    content: '爱不是寻找一个完美的人，而是学会用完美的眼光欣赏那个不完美的人。',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  // 新添加的心语时刻卡片
  {
    id: '9',
    category: 'deep-talk',
    title: '心语时刻',
    content: '用三个词形容你对我最初的印象，和现在相比有变化吗？',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '10',
    category: 'deep-talk',
    title: '心语时刻',
    content: '分享一个你最近感到脆弱或不安的时刻，你希望我当时怎么做？',
    animal: 'Rabbit',
    color: 'bg-rose-50',
  },
  {
    id: '11',
    category: 'deep-talk',
    title: '心语时刻',
    content: '在你看来，我表达爱意最常用（或最可爱）的方式是什么？',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '12',
    category: 'deep-talk',
    title: '心语时刻',
    content: '除了我，还有一个什么小梦想或心愿是你从未告诉别人的？',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '13',
    category: 'deep-talk',
    title: '心语时刻',
    content: '自从我们在一起，你觉得我最大的积极改变是什么？',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '14',
    category: 'deep-talk',
    title: '心语时刻',
    content: '最近一次，你心里偷偷感谢我或为我们关系感到庆幸，是因为什么事？',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '15',
    category: 'deep-talk',
    title: '心语时刻',
    content: '有没有一本书、一首歌或一部电影，你觉得特别能代表我的内心世界？',
    animal: 'Rabbit',
    color: 'bg-rose-50',
  },
  {
    id: '16',
    category: 'deep-talk',
    title: '心语时刻',
    content: '闭上眼睛，描绘一下五年后我们一个平凡的周末早晨是什么样子？',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '17',
    category: 'deep-talk',
    title: '心语时刻',
    content: '你觉得我身上有一个自己还没意识到的小优点或小缺点是什么？',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '18',
    category: 'deep-talk',
    title: '心语时刻',
    content: '当我心情低落时，做什么样的事或听到什么话最能安慰到我？',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '19',
    category: 'deep-talk',
    title: '心语时刻',
    content: '有没有一件小事，你曾想对我道歉或希望我道歉，但一直没开口？',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '20',
    category: 'deep-talk',
    title: '心语时刻',
    content: '你认为保持怎样的个人空间或爱好，能让我们的关系更健康？',
    animal: 'Rabbit',
    color: 'bg-rose-50',
  },
  {
    id: '21',
    category: 'deep-talk',
    title: '心语时刻',
    content: '从对方身上，你学到的最珍贵的一件事或一种品质是什么？',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '22',
    category: 'deep-talk',
    title: '心语时刻',
    content: '在关系里，你最大的安全感来源是什么？又曾悄悄担心过什么？',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '23',
    category: 'deep-talk',
    title: '心语时刻',
    content: '我们之间，哪个小仪式或习惯对你来说最重要、最不可替代？',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '24',
    category: 'deep-talk',
    title: '心语时刻',
    content: '当你面临重大挑战时，你最希望我用什么方式支持你？',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '25',
    category: 'deep-talk',
    title: '心语时刻',
    content: '我日常中一个你自己都没在意的小动作或小表情，却让我觉得特别可爱。',
    animal: 'Rabbit',
    color: 'bg-rose-50',
  },
  {
    id: '26',
    category: 'deep-talk',
    title: '心语时刻',
    content: '我们最近一次意见不同，事后让你对彼此有了什么新的认识？',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  // 新添加的森林挑战卡片
  {
    id: '27',
    category: 'challenge',
    title: '森林挑战',
    content: '面对面坐下，一人做缓慢的搞笑表情或动作，另一人必须像镜子一样同步模仿。',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '28',
    category: 'challenge',
    title: '森林挑战',
    content: '一方在对方手心慢慢写下"我爱你"或一个简单单词，让对方猜写的是什么。',
    animal: 'Rabbit',
    color: 'bg-pink-50',
  },
  {
    id: '29',
    category: 'challenge',
    title: '森林挑战',
    content: '合作完成一个简单的双人瑜伽姿势（如背靠背伸展、双人树式），并保持10秒。',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '30',
    category: 'challenge',
    title: '森林挑战',
    content: '轮流快速说出三件今天感谢对方的小事，不能重复，限时30秒。',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '31',
    category: 'challenge',
    title: '森林挑战',
    content: '十指相扣，安静地看着对方的眼睛，不说话，持续1分钟。',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '32',
    category: 'challenge',
    title: '森林挑战',
    content: '以"很久很久以前，在心语森林里…"开头，轮流每人说一句话，共同编一个童话故事。',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '33',
    category: 'challenge',
    title: '森林挑战',
    content: '快速问5个关于彼此喜好的问题（如"我最爱的水果？""我最怕的动物？"），同时写下答案，看正确率。',
    animal: 'Rabbit',
    color: 'bg-pink-50',
  },
  {
    id: '34',
    category: 'challenge',
    title: '森林挑战',
    content: '随机找一个可爱的动物表情包，两人同时模仿并拍照，看谁更像。',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '35',
    category: 'challenge',
    title: '森林挑战',
    content: '一人闭上眼睛，由另一人用语言引导（不能触碰）在房间内安全行走一小段路，取回一个小物件。',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '36',
    category: 'challenge',
    title: '森林挑战',
    content: '一人随意哼一段旋律，另一人用"啦"或"哒"即兴接上，合作完成一首无词歌。',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '37',
    category: 'challenge',
    title: '森林挑战',
    content: '一人当"黏土"，另一人当"雕塑家"，用肢体摆出一个指定主题（如"快乐"、"守护"）的造型。',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '38',
    category: 'challenge',
    title: '森林挑战',
    content: '轻轻拥抱，一方将耳朵贴在对方心口，安静地数30秒心跳，然后交换。',
    animal: 'Rabbit',
    color: 'bg-pink-50',
  },
  {
    id: '39',
    category: 'challenge',
    title: '森林挑战',
    content: '各自在卡片上写下对彼此一年后的祝福或期待，交换收藏，约定明年今日打开。',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  {
    id: '40',
    category: 'challenge',
    title: '森林挑战',
    content: '各自教对方一个自己擅长而对方不会的小技能（如折纸、一句方言、一个魔术手法），限时5分钟教学。',
    animal: 'Koala',
    color: 'bg-emerald-50',
  },
  {
    id: '41',
    category: 'challenge',
    title: '森林挑战',
    content: '为对方提供3分钟的肩膀或手部按摩，并接受对方的反馈（力度、位置）。',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '42',
    category: 'challenge',
    title: '森林挑战',
    content: '一起在一张纸上，用最简单的线条共同画出一个梦想中的房间或角落。',
    animal: 'Lion',
    color: 'bg-amber-50',
  },
  {
    id: '43',
    category: 'challenge',
    title: '森林挑战',
    content: '轮流不间断地说出对方的优点或可爱之处，每人至少说5个，不能犹豫。',
    animal: 'Rabbit',
    color: 'bg-pink-50',
  },
  {
    id: '44',
    category: 'challenge',
    title: '森林挑战',
    content: '共同发明一个只属于你们俩的、代表"我爱你"或"加油"的专属秘密手势，并立刻使用它。',
    animal: 'Fox',
    color: 'bg-orange-50',
  },
  // 新添加的森林寄语卡片
  {
    id: '45',
    category: 'wisdom',
    title: '森林寄语',
    content: '愿你们的爱情如同初见时那般纯粹与美好。',
    animal: 'Owl',
    color: 'bg-indigo-50',
  },
  {
    id: '46',
    category: 'wisdom',
    title: '森林寄语',
    content: '执子之手，与子偕老。',
    animal: 'Koala',
    color: 'bg-emerald-50',
  }
];
